from __future__ import annotations

from typing import Protocol

from dragback.domain import Artifact, Edge, EdgeKind


class GraphStore(Protocol):
    def reset(self, *, version: int, artifacts: list[Artifact], edges: list[Edge]) -> None: ...

    @property
    def version(self) -> int: ...

    @property
    def version_label(self) -> str: ...

    def increment_version(self) -> str: ...

    def add_artifact(self, artifact: Artifact) -> None: ...

    def update_artifact(self, artifact: Artifact) -> None: ...

    def get_artifact(self, artifact_id: str) -> Artifact: ...

    def list_artifacts(self) -> list[Artifact]: ...

    def add_edge(self, edge: Edge) -> None: ...

    def list_edges(self) -> list[Edge]: ...

    def outgoing_edges(
        self, artifact_id: str, kinds: set[EdgeKind] | None = None
    ) -> list[Edge]: ...

    def snapshot(self) -> dict[str, object]: ...
